### ISSUE TITLE
Project won't build

### ISSUE THREAD

**Issue by neonailol** [max-kammerer/kotlin-jvm-native#1]
I am trying to build this project via `./gradlew build`
And it fails with message `> Plugin with id 'kotlin-platform-native-experimental' not found.`
How can i fix this issue?

**Comment by max-kammerer** [comment]
Hi, this is experimental test project, plugin 'kotlin-platform-native...' is not ready yet.
You can enable MPP in native manually similar to https://github.com/max-kammerer/orion-viewer/blob/mig4/native/native.build.gradle (several last lines)

**Comment by neonailol** [comment]
Big thanks, now it kinda compiles, will be waiting for this plugin to release.
Getting errors when have common src dir in gradle, but if i comment it out build passes.
Errors is `exception: java.lang.IllegalArgumentException: Global 'ktype:nnl.rocks.kactoos.Scalar' already exists`
